language: ruby
cache: bundler
sudo: false
rvm: 2.2

before_install:


deploy:
  provider: pages
  skip_cleanup: true # always set to true
  github_token: 24b7d3fd74263fa941f9c9cda3bff5fc6f0a2971 # Set in travis-ci.org dashboard
  on:
    branch: master


install: script/bootstrap
script: script/cibuild

addons:
  ssh_known_hosts: madsynn.github.io


bundler_args: --without development debug


branches:
  only:
    - master
