language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3

before_script:
 - chmod +x ./script/cibuild
 - chmod +x ./script/bootstrap

install: /script/bootstrap
script: /script/cibuild

# branches:
#   only:
#   - gh-pages
#   - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
