language: ruby
cache: bundler
sudo: false
rvm:
  - 2.3.3

install: ./script/bootstrap
script: ./script/cibuild

before_script:
 - chmod +x ./script/cibuild
 - chmod +x ./script/bootstrap



# branches:
#   only:
#   - gh-pages
#   - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
