# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge
google_analytics: UA-104942085-1
show_downloads: false

# Permalinks
permalink:        pretty

title: '[ KAWG ]'
tagline:  Kingdoms At War Guide
description:      "This is a Guide / Overview of helpful stuff to make the gamers of Kingdoms At war lives a little bit easier..."
url:  https://madsynn.github.io/kaw-reference/
baseurl:          /
excerpt_separator: "\n\n"

# author:
#   name:           'Affordable Programmer'
#   url:            https://twitter.com/AffordProg

# paginate:         5

liquid:
  error_mode: warn

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/madsynn/kaw-reference.git

encoding: utf-8

incremental: true

collections:
  eb:
    output: true
    permalink: /:collection/:title

defaults:
  -
    scope:
      path: "eb"
      type: "eb"
    values:
      layout: "eb"
      author: "MaDsYnN"
