---
author:
  name: "Affordable Programmer"
  url: "https://twitter.com/AffordProg"
baseurl: /
collections:
  ebs:
    output: true
    permalink: "/ebs/:path/"
defaults:
  -
    scope:
      path: ""
      type: ebs
    values:
      layout: epic-battle
description: "Kingdoms at War Guide & Overview of helpful stuff to make the gamers of Kingdoms At war lives a little bit easier..."

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata

github:
  repo: "https://github.com/karloespiritu/blackdoc"

google_analytics: UA-104942085-1
highlighter: rouge
paginate: 5
permalink: pretty
tagline: "Kingdoms At War Guide"
title: KAWG
url: "https://madsynn.github.io/kaw-reference/"
version: "1.0.1"

