# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge
google_analytics: UA-104942085-1

encoding: utf-8

# Permalinks
permalink:        pretty

title: '[ KAWG ]'
tagline:  Kingdoms At War Guide
description:      "Kingdoms at War Guide & Overview of helpful stuff to make the gamers of Kingdoms At war lives a little bit easier..."
# tags: "kaw, kingdoms at war, kawg, kingdoms at war guide, epic battles guides, eb guides"

url:  https://madsynn.github.io/kaw-reference/
baseurl:          /
excerpt_separator: <!--more-->


author:
  name:           'Affordable Programmer'
  url:            https://twitter.com/AffordProg

# paginate:         5

liquid:
  error_mode: warn

# Custom vars
# version:          1.0.1

github:
  repo:           https://github.com/madsynn/kaw-reference.git

collections:
  ebs:
   permalink: /:collection/:title

permalinks:
  eb: /:collection/:year/:month/:title/



plugins:
  - jekyll-sitemap


