---
title: KAWG
tagline: "Kingdoms At War Guide"
description: "Kingdoms at War Guide & Overview of helpful stuff to make the gamers of Kingdoms At war lives a little bit easier..."
url: "https://madsynn.github.io/kaw-reference/"

google_analytics: UA-104942085-1
highlighter: rouge
paginate: 5
permalink: pretty
version: "1.0.1"

author:
  name: "Affordable Programmer"
  url: "https://twitter.com/AffordProg"
baseurl: /

collections:
  ebs:
    output: true
    permalink: "/ebs/:path/"
    sort_by: "category"
  lands:
    output: true
    permalink: "/lands/:path/"
    sort_by: "category"

webmaster_verifications:
  google:
  bing:

social:
  name: Phillip Madsen
  links:
    - https://www.facebook.com/phillip.madsen.ut
    - https://www.linkedin.com/in/phillipmadsen
    - https://github.com/madsynn

defaults:
  -
    scope:
      path: ""
      type: ebs
    values:
      layout: epic-battle

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap

github:
  repo: "https://github.com/karloespiritu/blackdoc"

